; journalism.utexas.edu.make
;

; This file was auto-generated by drush make
core = 6.x
api = 2

; Core
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pressflow][download][type] = ""
projects[pressflow][download][url] = ""
projects[pressflow][type] = "core"

; Modules
projects[admin_menu][version] = "1.9"

projects[block_class][version] = "1.4"

projects[ctools][version] = "1.13"

projects[ckeditor][version] = "1.15"

projects[ckeditor_link][version] = "1.2"

projects[cck][version] = "2.10"

projects[context][version] = "3.3"

projects[date][version] = "2.10"

projects[db_maintenance][version] = "1.4"

projects[emfield][version] = "2.4"

projects[filefield][version] = "3.13"

projects[filefield_sources][version] = "1.10"

projects[google_cse][version] = "1.x-dev"

projects[htmlpurifier][version] = "2.4"

projects[imageapi][version] = "1.10"

projects[imagefield][version] = "3.11"

projects[imce][version] = "2.7"

projects[jquery_ui][version] = "1.5"

projects[ldap_integration][version] = "1.0-beta3"

projects[link][version] = "2.11"

projects[media_vimeo][version] = "1.1"

projects[noreqnewpass][version] = "2.0"

projects[override_node_options][version] = "1.14"

projects[panels][version] = "3.10"

projects[pathauto][version] = "2.0"

projects[securepages][version] = "1.9"

projects[shadowbox][version] = "4.2"

projects[token][version] = "1.19"

projects[views][version] = "2.18"

projects[views_slideshow][version] = "2.4"

projects[views_slideshow_ddblock][version] = "2.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cookie_cache_bypass][download][type] = ""
projects[cookie_cache_bypass][download][url] = ""
projects[cookie_cache_bypass][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[path_alias_cache][download][type] = ""
projects[path_alias_cache][download][url] = ""
projects[path_alias_cache][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[jour][download][type] = ""
projects[jour][download][url] = ""
projects[jour][type] = "theme"

