; redesign-advertising.utexas.edu.make
;

; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas][download][type] = ""
projects[utexas][download][url] = ""
projects[utexas][type] = "module"

projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.9"

projects[ckeditor][version] = "1.16+14-dev"

projects[ckeditor_link][version] = "2.3"

projects[ckeditor_link_file][version] = "1.3+3-dev"

projects[ckeditor_link_user][version] = "1.0"

projects[node_clone][version] = "1.0-rc2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[content_type_landing_page][download][type] = ""
projects[content_type_landing_page][download][url] = ""
projects[content_type_landing_page][type] = "module"
projects[content_type_landing_page][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[content_type_standard_page][download][type] = ""
projects[content_type_standard_page][download][url] = ""
projects[content_type_standard_page][type] = "module"
projects[content_type_standard_page][version] = "1.1"

projects[context][version] = "3.6"

projects[context_field][version] = "1.0"

projects[ctr][version] = "3.3"

projects[date][version] = "2.8"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.7"

projects[features_roles_permissions][version] = "1.2"

projects[field_collection][version] = "1.0-beta10"

projects[field_collection_node_clone][version] = "1.0-beta1"

projects[fieldblock][version] = "1.4"

projects[file_entity][version] = "2.0-beta2"

projects[globalredirect][version] = "1.5"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[media][version] = "2.0-beta1+9-dev"

projects[media_ckeditor][version] = "2.0-alpha1"

projects[media_youtube][version] = "3.0"

projects[menu_block][version] = "2.7"

projects[metatag][version] = "1.4"

projects[migrate][version] = "2.8"

projects[migrate_d2d][version] = "2.1-beta1+43-dev"

projects[module_filter][version] = "2.0"

projects[multiple_fields_remove_button][version] = "1.5"

projects[node_clone_tab][version] = "1.1"

projects[pathauto][version] = "1.3"

projects[redirect][version] = "1.0-rc3"

projects[security_review][version] = "1.2"

projects[smartcrop][version] = "1.0-beta2"

projects[special_menu_items][version] = "2.0"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_qualtrics_filter][download][type] = ""
projects[utexas_qualtrics_filter][download][url] = ""
projects[utexas_qualtrics_filter][type] = "module"
projects[utexas_qualtrics_filter][version] = "1.0"

projects[video_filter][version] = "3.1"

projects[views][version] = "3.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_admin][download][type] = ""
projects[utexas_admin][download][url] = ""
projects[utexas_admin][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_background_accent][download][type] = ""
projects[utexas_background_accent][download][url] = ""
projects[utexas_background_accent][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_beacon][download][type] = ""
projects[utexas_beacon][download][url] = ""
projects[utexas_beacon][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_contact_info][download][type] = ""
projects[utexas_contact_info][download][url] = ""
projects[utexas_contact_info][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_devel][download][type] = ""
projects[utexas_devel][download][url] = ""
projects[utexas_devel][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_featured_highlight][download][type] = ""
projects[utexas_featured_highlight][download][url] = ""
projects[utexas_featured_highlight][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_flex_content_areas][download][type] = ""
projects[utexas_flex_content_areas][download][url] = ""
projects[utexas_flex_content_areas][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_fonts][download][type] = ""
projects[utexas_fonts][download][url] = ""
projects[utexas_fonts][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_google_cse][download][type] = ""
projects[utexas_google_cse][download][url] = ""
projects[utexas_google_cse][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_google_tag_manager][download][type] = ""
projects[utexas_google_tag_manager][download][url] = ""
projects[utexas_google_tag_manager][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_hero_photo][download][type] = ""
projects[utexas_hero_photo][download][url] = ""
projects[utexas_hero_photo][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_image_links][download][type] = ""
projects[utexas_image_links][download][url] = ""
projects[utexas_image_links][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_menu][download][type] = ""
projects[utexas_menu][download][url] = ""
projects[utexas_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_newsreel][download][type] = ""
projects[utexas_newsreel][download][url] = ""
projects[utexas_newsreel][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_page_builder][download][type] = ""
projects[utexas_page_builder][download][url] = ""
projects[utexas_page_builder][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_photo_content_area][download][type] = ""
projects[utexas_photo_content_area][download][url] = ""
projects[utexas_photo_content_area][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_promo_field][download][type] = ""
projects[utexas_promo_field][download][url] = ""
projects[utexas_promo_field][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_promo_list][download][type] = ""
projects[utexas_promo_list][download][url] = ""
projects[utexas_promo_list][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_quick_links][download][type] = ""
projects[utexas_quick_links][download][url] = ""
projects[utexas_quick_links][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_resource][download][type] = ""
projects[utexas_resource][download][url] = ""
projects[utexas_resource][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_social_accounts][download][type] = ""
projects[utexas_social_accounts][download][url] = ""
projects[utexas_social_accounts][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_social_links][download][type] = ""
projects[utexas_social_links][download][url] = ""
projects[utexas_social_links][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_tablesaw_filter][download][type] = ""
projects[utexas_tablesaw_filter][download][url] = ""
projects[utexas_tablesaw_filter][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_templates][download][type] = ""
projects[utexas_templates][download][url] = ""
projects[utexas_templates][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_twitter_widget][download][type] = ""
projects[utexas_twitter_widget][download][url] = ""
projects[utexas_twitter_widget][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utexas_utdk_deploy][download][type] = ""
projects[utexas_utdk_deploy][download][url] = ""
projects[utexas_utdk_deploy][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[utlogin][download][type] = ""
projects[utlogin][download][url] = ""
projects[utlogin][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[STARTERKIT][download][type] = ""
projects[STARTERKIT][download][url] = ""
projects[STARTERKIT][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[forty_acres][download][type] = ""
projects[forty_acres][download][url] = ""
projects[forty_acres][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[moody_alpha_subtheme][download][type] = ""
projects[moody_alpha_subtheme][download][url] = ""
projects[moody_alpha_subtheme][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tablesaw][download][type] = ""
libraries[tablesaw][download][url] = ""
libraries[tablesaw][directory_name] = "tablesaw"
libraries[tablesaw][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[GalleryView][download][type] = ""
libraries[GalleryView][download][url] = ""
libraries[GalleryView][directory_name] = "GalleryView"
libraries[GalleryView][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier-4.6.0][download][type] = ""
libraries[htmlpurifier-4.6.0][download][url] = ""
libraries[htmlpurifier-4.6.0][directory_name] = "htmlpurifier-4.6.0"
libraries[htmlpurifier-4.6.0][type] = "library"

